src/Entity/ParkingSublease.php
<?php


namespace App\Entity;


use DateTimeImmutable;
use Doctrine\ORM\Mapping\OrderBy;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Exception;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ParkingSubleaseRepository")
 * @ORM\Table(name="parkingsublease", uniqueConstraints={@UniqueConstraint(name="idx_day_user", columns={"day_id", "user_id"})})
 */
class ParkingSublease
{

    const PRICE = 5.0;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }


    /**
     * @ORM\Column(type="datetime_immutable")
     * @OrderBy({"name" = "ASC"})
     */
    private $creationDate;


    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $paidAt;


    /**
     * @return DateTimeImmutable|null
     */
    public function getDate(): ?DateTimeImmutable
    {
        return $this->creationDate;
    }


    /**
     * @ORM\ManyToOne(targetEntity="Day", inversedBy="parkingSublease", cascade={"persist"})
     */
    private $day;


    /**
     * @return Day
     */
    public function getDay(): Day
    {
        return $this->day;
    }


    /**
     * @ORM\Column(type="integer")
     */
    private $subleaseParkingNumber;



    /**
     * @return int
     */
    public function getSubleaseParkingNumber(): int
    {
        return $this->subleaseParkingNumber;
    }



    /**
     * @return int|null
     */
    public function getRenterParkingNumber(): ?int
    {
        return $this->user->getParkingNumber();
    }


    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }


    /**
     * @param User $user
     */
    public function setUser(User $user): void
    {
        $this->user = $user;
    }


    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="parkingSublease", cascade={"persist"})
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="parkingSubleaseAsTaker", cascade={"persist"})
     */
    private $taker;


    /**
     * @return User|null
     */
    public function getTaker(): ?User
    {
        return $this->taker;
    }


    /**
     * @param User $taker
     */
    public function setTaker(User $taker): void
    {
        $this->taker = $taker;
    }


    /**
     * @ORM\Column(type="float")
     */
    private $price;


    /**
     * @return float
     */
    public function getPrice(): float
    {
        return $this->price;
    }


    /**
     * @param float $price
     */
    private function setPrice(float $price): void
    {
        $this->price = $price;
    }


    /**
     * @ORM\Column(type="boolean")
     */
    private $isSubleaseOpened;


    public function subleaseRetract(): void
    {
        $this->isSubleaseOpened = true;
        $this->isTaken = false;
        $this->taker = null;
        $this->paidAt = null;
        $this->dueDate = null;
    }


    /**
     * @return bool
     */
    public function getIsSubleaseOpened(): bool
    {
        return $this->isSubleaseOpened;
    }


    public function sublease(): void
    {
        $this->isSubleaseOpened = true;
        $this->price = self::PRICE;
    }


    public function unSublease(): void
    {
        $this->isSubleaseOpened = false;
    }


    /**
     * @ORM\Column(type="boolean")
     */
    private $isTaken;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $dueDate;


    /**
     * @return bool
     */
    public function getIsTaken(): bool
    {
        return $this->isTaken;
    }



    public function setIsTaken(): void
    {
        $this->isTaken = true;
        $this->unSublease();
    }


    public function markAsPaid(): void
    {
        $this->paidAt = new DateTimeImmutable();
        if ($this->dueDate !== null) {
            $this->dueDate = null;
        }
    }


    public function markAsNotPaid(): void
    {
        $this->paidAt = null;
        $this->setDueDate();
    }


    public function getIsPaid(): bool
    {
        return $this->paidAt !== null;
    }


    public function getIsNotPaid(): bool
    {
        return $this->paidAt === null;
    }


    public function getPaidAt(): DateTimeImmutable
    {
        return $this->paidAt;
    }



    /**
     * ParkingSublease constructor.
     * @param Day $day
     * @param User $user
     * @throws Exception
     */
    public function __construct(Day $day, User $user)
    {
        $this->day = $day;
        $this->isSubleaseOpened = true;
        $this->isTaken = false;
        $this->creationDate = new DateTimeImmutable();
        $this->user = $user;
        $this->subleaseParkingNumber = $user->getParkingNumber();
        $this->price = self::PRICE;
        $this->paidAt = null;
    }

    public function getDueDate(): ?DateTimeImmutable
    {
        return $this->dueDate;
    }

    public function setDueDate(): self
    {
        $dayDueDate = $this->day->getDate();
        $dayDueDate = $dayDueDate->modify('last day of this month');
        $dayDueDate = $dayDueDate->modify('+ 10 days');

        $this->dueDate = $dayDueDate;

        return $this;
    }
}

templates/AdministratorRentals.twig
{% extends 'Format.twig' %}

{% block body %}

    {% if is_referer_calendar %}
        <p>
            <a href="{{ referer }}">
                <button type="button" class="btn waves-effect waves-light btn-dark xx-large-font">
                    Retour
                </button>
            </a>
        </p>
    {% else %}
        <span class="fewverticalspaces"></span>
    {% endif %}
    <div class="contentplace">
        <h2 class="mb-4 evidenced top-margin-cal">Tous les prêts</h2>
        <ul class="list-group">
            {% for sublease in subleases_list %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {% if sublease.isTaken %}
                        <span class="is-taken-container">
                            <span class="badge badge-success badge-pill">
                                {{ sublease.day.date|date('d-m-Y') }}
                            </span>
                            <span class="sublease-user text-primary">
                                <strong>{{ sublease.user.firstName }}
                                    {{ sublease.user.lastName }}</strong>
                            </span>
                            prête son parking à
                            <span class="sublease-taker text-primary">
                                <strong>{{ sublease.taker.firstName }}
                                    {{ sublease.taker.lastName }}</strong>
                            </span>
                        </span>
                    {% else %}
                        <span class="available-container text-secondary">
                            <span class="badge badge-secondary badge-pill">
                                {{ sublease.day.date|date('d-m-Y') }}
                            </span>
                            <span class="sublease-user">
                                <strong>{{ sublease.user.firstName }}
                                    {{ sublease.user.lastName }}</strong>
                            </span>
                            propose de prêter son parking
                        </span>
                    {% endif %}
                    <span class="badge badge-primary badge-pill">
                        Parking
                        {{ sublease.day.date > 'now'|date
                        ? sublease.getRenterParkingNumber()
                        : sublease.subleaseParkingNumber()
                        }}
                    </span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="bottom-margin"></div>
{% endblock %}

templates/CalendarConsulting.twig
{% extends 'Format.twig' %}

{#{% form_theme formular 'bootstrap_4_layout.html.twig' %}#}

{% block body %}

    <div class="d-flex flex-row align-items-center justify-content-between mx-sm-3 top-margin-cal">
        <h1 class="badge badge-dark bottom-margin-cal xx-large-font">{{ Calendar.toString }}</h1>
        <div>
            <a class="fas fa-fast-backward xx-large-font black" href="{{ path('calendar',
                {year:Calendar.previousMonth.year, month:Calendar.previousMonth.month}) }}" role="button">
            </a>
            <a class="fas fa-fast-forward xx-large-font black" href="{{ path('calendar',
                {year:Calendar.nextMonth.year, month:Calendar.nextMonth.month}) }}" role="button">
            </a>
        </div>
    </div>
    <div class="d-flex flex-row align-items-center justify-content-between mx-sm-3">
        {% if User is defined %}
            {% if (User.role == 'ROLE_ADMINISTRATOR' or User.role == 'ROLE_TENANT') %}
                {% if (CurrentYearInt == SelectedYearInt or NextYearInt == SelectedYearInt)
                    and (CurrentMonthInt == SelectedMonthInt or NextMonthInt == SelectedMonthInt) %}
                    {% if not User.isUserEnabled %}
                        <span class="badge-info-calendar">Compte utilisateur désactivé</span>
                    {% elseif User.isUserEnabled and User.isUserBlockedForInsolvency %}
                        <span class="badge-info-calendar xx-large-font">
                            Bloqué pour insolvabilité
                        </span>
                    {% elseif is_granted('ROLE_ADMINISTRATOR') %}
                        {% if CurrentMonthTotalOpenToSublease > 0 %}
                            {% if CurrentMonthTotalOpenToSublease > 1 %}
                                <span class="badge sublease-pill-badge evidenced x-large-font">{{ CurrentMonthTotalOpenToSublease }}
                                    prêts proposés
                                </span>
                            {% else %}
                                <span class="badge sublease-pill-badge evidenced x-large-font">
                                    Un prêt proposé
                                </span>
                            {% endif %}
                        {% else %}
                            <span class="badge sublease-pill-badge evidenced x-large-font">
                                Aucun prêt proposé pour le moment
                            </span>
                        {% endif %}
                    {% elseif is_granted('ROLE_TENANT') and not is_granted('ROLE_ADMINISTRATOR') %}
                        {% if CurrentMonthTotalOpenToSubleaseForTenant > 0 %}
                            {% if CurrentMonthTotalOpenToSubleaseForTenant > 1 %}
                                <span class="badge sublease-pill-badge evidenced x-large-font">
                                        {{ CurrentMonthTotalOpenToSubleaseForTenant }}
                                    nouveaux emprunts possibles
                                </span>
                            {% else %}
                                <span class="badge sublease-pill-badge evidenced x-large-font">
                                    Un nouvel emprunt possible
                                </span>
                            {% endif %}
                        {% else %}
                            <span class="badge sublease-pill-badge evidenced x-large-font">
                                Aucun nouvel emprunt possible pour le moment
                            </span>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% elseif (User.role == 'ROLE_ADMINISTRATOR' or User.role == 'ROLE_RENTER') %}
                {% if (CurrentYearInt == SelectedYearInt or NextYearInt == SelectedYearInt)
                    and (CurrentMonthInt == SelectedMonthInt or NextMonthInt == SelectedMonthInt) %}
                    {% if not User.isUserEnabled %}
                        <span class="badge-info-calendar">
                            Compte utilisateur désactivé
                        </span>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% else %}
            {% if (CurrentYearInt == SelectedYearInt or NextYearInt == SelectedYearInt)
                and (CurrentMonthInt == SelectedMonthInt or NextMonthInt == SelectedMonthInt) %}
                {% if CurrentMonthTotalOpenToSublease > 0 %}
                    {% if CurrentMonthTotalOpenToSublease > 1 %}
                        <span class="badge sublease-pill-badge evidenced x-large-font">{{ CurrentMonthTotalOpenToSublease }}
                            prêts proposés
                        </span>
                    {% else %}
                        <span class="badge sublease-pill-badge evidenced x-large-font">
                            Un prêt proposé
                        </span>
                    {% endif %}
                {% else %}
                    <span class="badge sublease-pill-badge evidenced x-large-font">
                        Aucun prêt proposé pour le moment
                    </span>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>

    <p class="bottom-margin-cal"></p>
    {% if User is defined %}
        {% if User.role == 'ROLE_RENTER' %}
            {% include 'RenterCalendar.twig' with
                {'Calendar' : Calendar, 'ParkingSubleaseRepository' : ParkingSubleaseRepository,
                    'User' : User, 'AllDays' : AllDays, 'Today' : Today,
                    'IsExistingOrHasExistedSubleaseByDayAndByUserList' : IsExistingOrHasExistedSubleaseByDayAndByUserList,
                    'TodayPlusOneMonth' : TodayPlusOneMonth, 'TakenDaysOfCurrentMonth' : TakenDaysOfCurrentMonth } only %}
        {% elseif User.role == 'ROLE_TENANT' %}
            {% include 'TenantCalendar.twig' with
                {'Calendar' : Calendar, 'ParkingSubleaseRepository' : ParkingSubleaseRepository, 'User' : User,
                    'AllDays' : AllDays, 'Today' : Today, 'IsSubleaseOpenedByDayList' : IsSubleaseOpenedByDayList,
                    'IsExistingTakenSubleaseByDayAndByTakerList' : IsExistingTakenSubleaseByDayAndByTakerList,
                    'TodayPlusOneMonth' : TodayPlusOneMonth, 'TakenDaysOfCurrentMonth' : TakenDaysOfCurrentMonth} only %}
        {% elseif is_granted('ROLE_ADMINISTRATOR') %}
            {% include 'AdministratorCalendar.twig' with
                {'Calendar' : Calendar, 'ParkingSubleaseRepository' : ParkingSubleaseRepository, 'User' : User,
                    'AllDays' : AllDays, 'OpenToSubleaseList' : OpenToSubleaseList,
                    'TakenOrOpenedSubleaseList' : TakenOrOpenedSubleaseList, 'Today' : Today,
                    'TakenDaysOfCurrentMonth' : TakenDaysOfCurrentMonth} only %}
        {% endif %}
    {% else %}
        {% include 'LoggedOutCalendar.twig' with
            {'Calendar' : Calendar, 'Today' : Today, 'OpenToSubleaseList' : OpenToSubleaseList,
                'TakenDaysOfCurrentMonth' : TakenDaysOfCurrentMonth } only %}
    {% endif %}
{% endblock %}

templates/Login.twig
{% extends 'Format.twig' %}

{% block body %}

    {% if not isRefererLogin %}
        <p xmlns:font-size="http://www.w3.org/1999/xhtml">
            <a href="{{ referer }}">
                <button type="button" class="btn waves-effect waves-light btn-dark xx-large-font evidenced">
                    Retour
                </button>
            </a>
        </p>
    {% else %}
        <p xmlns:font-size="http://www.w3.org/1999/xhtml">
            <span>
                <button type="button" class="btn waves-effect waves-light btn-dark disabled xx-large-font evidenced">
                    Retour
                </button>
            </span>
        </p>
    {% endif %}
    <div class="contentplace">
        <span class="fewverticalspaces"></span>
        {% if error %}
            <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}
        <form action="{{ path('login') }}" method="post">
            <div class="form-group">
                <input type="text" class="form-control" id="username" name="_username"
                       value="" aria-describedby="emailHelp" placeholder="Nom d'utilisateur">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password" name="_password"
                       value="" placeholder="Mot de passe">
            </div>
            <button type="submit" class="btn waves-effect waves-light btn-dark xx-large-font evidenced">
                Connecter
            </button>
        </form>
    </div>
    <span class="fewverticalspaces"></span>
    <div class="updatebuttonplace">
        <a target="_blank" href="https://www.giuruss.ch/dem.mp4">
            <button type="button" class="btn waves-effect waves-light btn-danger xx-large-font evidenced">
                Vidéo de démo
            </button>
        </a>
    </div>
    <span class="verticalspaces"></span>
{% endblock %}

templates/RenterRentals.twig
{% extends 'Format.twig' %}

{% block body %}
    {% if IsRefererCalendar %}
        <p>
            <a href="{{ Referer }}">
                <button type="button" class="btn waves-effect waves-light btn-dark xx-large-font evidenced">
                    Retour
                </button>
            </a>
        </p>
    {% else %}
        <span class="fewverticalspaces"></span>
    {% endif %}
    <div class="contentplace">
        <h1 class="top-margin-cal evidenced bottom-margin-cal">Mes prêts actuels</h1>
        {% if CurrentPeriodSubleasesList is defined %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="evidenced black">Date du prêt</span>
                <span class="evidenced black">Emprunteur</span>
            </li>
            {% for sublease in CurrentPeriodSubleasesList %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span class="badge badge-success badge-pill">
                        {{ sublease.day.date|date('d-m-Y') }}
                    </span>
                    <span class="sublease-user badge badge-primary badge-pill">
                        {{ sublease.taker.firstName }} {{ sublease.taker.lastName }}
                    </span>
                </li>
            {% endfor %}
        {% endif %}
    </div>
    <span class="verticalspaces"></span>
{% endblock %}

templates/TenantCalendar.twig
{% block body %}
    {% if Calendar is defined %}
        <table>
            <thead>
            <tr>
                <th class="table-size"><span class="evidenced x-large-font">Lundi</span></th>
                <th class="table-size"><span class="evidenced x-large-font">Mardi</span></th>
                <th class="table-size"><span class="evidenced x-large-font">Mercredi</span></th>
                <th class="table-size"><span class="evidenced x-large-font">Jeudi</span></th>
                <th class="table-size"><span class="evidenced x-large-font">Vendredi</span></th>
                <th class="table-size"><span class="evidenced x-large-font">Samedi</span></th>
                <th class="table-size"><span class="evidenced x-large-font">Dimanche</span></th>
            </tr>
            </thead>
            <tbody>
            {# sauter des cases jusqu'au début du mois #}
            {# Afficher les jours donnés par le controller ligne par ligne #}

            {% for date in Calendar.datesList %}
                {% if date|date('N') == 1 or loop.first %}
                    <tr>
                {% endif %}
                {% if loop.first and date|date('N') > 1 %}
                    {% for d in 1..(date|date('N') - 1) %}
                        <td></td>
                    {% endfor %}
                {% endif %}
                <td>
                    <div class="calendar__table">
                        <div>
                            <span class="evidenced">{{ date|date('j') }}</span>
                            {% if date|date('N') == 1 or loop.first %}
                                <span class="evidenced">(Sem {{ date|date('W') }})</span>
                            {% endif %}
                            {% set dayFormat = date|date('Y-m-d') %}
                            {% if IsSubleaseOpenedByDayList[dayFormat] is defined %}
                                {% if IsSubleaseOpenedByDayList[dayFormat].isSubleaseOpened %}
                                    {% if date >= Today %}
                                        {% if IsExistingTakenSubleaseByDayAndByTakerList[dayFormat] is not defined %}
                                            <div class="centrage">
                                                <button type="button" class="btn sublease-pill-badge medium-font"
                                                        data-toggle="modal" data-target="#singlePlaceModal1{{ dayFormat }}">
                                                    <span class="fas fa-handshake medium-font">
                                                        <span class="line-break">
                                                            Emprunter
                                                        </span>
                                                    </span>
                                                </button>
                                            </div>

                                            <div class="modal fade" id="singlePlaceModal1{{ dayFormat }}" tabindex="-1"
                                                 role="dialog" aria-labelledby="singlePlaceModalLabel1{{ dayFormat }}"
                                                 aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title"
                                                                id="singlePlaceModalLabel1{{ dayFormat }}">
                                                                <span class="evidenced">Emprunt</span>
                                                            </h5>
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <span class="evidenced line-break bottom-margin-cal">
                                                                Date : {{ date|date('d / m / Y') }} &nbsp;(Journée entière)
                                                            </span>
                                                            Valider l'emprunt du parking au prix de
                                                            <span class="evidenced">
                                                                {{ constant('App\\Entity\\ParkingSublease::PRICE') }}.-- CHF
                                                            </span>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary"
                                                                    data-dismiss="modal">
                                                                Annuler
                                                            </button>
                                                            {% if User.isUserEnabled and not User.isUserBlockedForInsolvency %}
                                                                <a class="btn btn-primary"
                                                                   href="{{ path('day_take',
                                                                       { dateString: date|date('Y-m-d') }) }}">
                                                                    Valider
                                                                </a>
                                                            {% elseif not User.isUserEnabled %}
                                                                <span class="badge-info-calendar">
                                                                    Compte utilisateur désactivé
                                                                </span>
                                                            {% elseif User.isUserBlockedForInsolvency %}
                                                                <span class="badge badge-info x-large-font">
                                                                    Bloqué pour insolvabilité
                                                                </span>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endif %}
                                {% endif %}
                            {% endif %}

                            {% if IsExistingTakenSubleaseByDayAndByTakerList[dayFormat] is defined %}
                                <div class="centrage">
                                    <span data-toggle="tooltip" data-html="true" title="Mon parking emprunté">
                                        <span type="badge badge-info" class="badge badge badge-outline-dark">
                                            <span class="calendar-badge badge-light">
                                                <span class="fas fa-car-side"></span>
                                                <span class="line-break"></span>
                                                {% if date > Today %}
                                                    <span class="badge badge-pill badge-danger line-break">
                                                        <span class="">
                                                            Parking
                                                            {{ IsExistingTakenSubleaseByDayAndByTakerList[dayFormat].getRenterParkingNumber }}
                                                        </span>
                                                    </span>
                                                    <span class="badge badge-pill badge-dark"></span>
                                                    <span class="one-line-space"></span>
                                                    <span class="line-break small">
                                                        <span class="evidenced">prêté par</span>
                                                    </span>
                                                    <span class="line-break small">
                                                        <span class="evidenced">
                                                            {{ IsExistingTakenSubleaseByDayAndByTakerList[dayFormat].getUser }}
                                                        </span>
                                                    </span>
                                                {% else %}
                                                    <span class="badge badge-pill badge-danger line-break">
                                                        <span class="">
                                                            Parking
                                                            {{ IsExistingTakenSubleaseByDayAndByTakerList[dayFormat].subleaseParkingNumber }}
                                                        </span>
                                                    </span>
                                                    <span class="badge badge-pill badge-dark"></span>
                                                    <span class="one-line-space"></span>
                                                    <span class="line-break small">
                                                        <span class="evidenced">prêté par</span>
                                                    </span>
                                                    <span class="line-break small evidenced">
                                                        <span class="evidenced">
                                                            {{ IsExistingTakenSubleaseByDayAndByTakerList[dayFormat].getUser }}
                                                        </span>
                                                    </span>
                                                {% endif %}
                                            </span>
                                        </span>
                                    </span>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </td>
                {% if date|date('N') == 7 or loop.last %}
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <span class="verticalspaces"></span>
    {% endif %}
{% endblock %}

templates/UserCreate.twig
{% extends 'Format.twig' %}

{% block body %}

    <span class="fewverticalspaces"></span>

    {% if Role == 'ROLE_RENTER' %}
        <h1 class="evidenced top-margin-cal">Création d'un utilisateur prêteur</h1>
    {% endif %}

    {% if Role == 'ROLE_TENANT' %}
        <h1 class="evidenced top-margin-cal">Création d'un utilisateur emprunteur</h1>
    {% endif %}

    <br>

    {{ form_start(formular) }}

    <div class="form-row">
        <div class="form-group col-md-6">
            {{ form_row(formular.username) }}
        </div>
    </div>
    <br>
    <div class="form-group">
        <div class="form-row">
            <div class="form-group col-md-3">
                {{ form_row(formular.password.first) }}
            </div>
            <div class="form-group col-md-3">
                {{ form_row(formular.password.second) }}
            </div>
        </div>
    </div>
    <div class="form-group">
        {{ form_row(formular.firstName) }}
    </div>
    <div class="form-group">
        {{ form_row(formular.lastName) }}
    </div>

    {% if Role == 'ROLE_RENTER' %}
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form_row(formular.parkingNumber) }}
            </div>
        </div>
    {% endif %}
    <button type="submit" class="btn waves-effect waves-light btn-dark" style="font-size: x-large">Enregistrer</button>

    {{ form_widget(formular) }}

    {{ form_end(formular) }}

    <div class="verticalspaces"></div>

{% endblock %}

templates/Welcome.twig
{#{% extends 'Format.twig' %}#}

{% block body %}


    <div class="contentplace">

        <h2><b>Bienvenue {{ Test }}</b></h2>

    </div>



{% endblock %}